---
  - name: "create www directory"
    file:
      path: /var/www/html/{{ domain }}
      state: directory
      mode: '0775'

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload nginx

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      mode: '0644'
    notify: reload nginx
