---
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx,wget,zsh"
    tags: packages
    apt: name="{{ packages }}"
    vars:
     packages:
      - nginx
      - wget
      - zsh
     state: present
